Given a string of size n, write functions to perform following operations on string. Left (Or anticlockwise) rotate the given string by d elements (where d <= n). Right (Or clockwise) rotate the given string by d elements (where d <= n). 

Examples: Input : 
s = "whatismyname" d = 2 Output : Left Rotation : "atismynamewh" Right Rotation : "mewhatismyna" Input : s = "qwertyu" d = 2 Output : Left rotation : "ertyuqw" Right rotation : "yuqwert" 

In [9]:
def stringtotate(var_str,d,rot="acw"):
    n = len(var_str)
    if rot=="acw":
        str1,str2  = var_str[:d],var_str[d:]
        return str2+str1
    elif rot == "cw":
        str1,str2  = var_str[-d:],var_str[:-d]
        return (str1+str2)
    
print(stringtotate("whatismyname",2,"cw"))
print(stringtotate("whatismyname",2,"acw"))

mewhatismyna
atismynamewh


Write a function that accepts two parameters N,M. To create a matrix of size N x M. The (0,0) element should start at 1 and the next elements should be incremented by one. For example, if N =3, M=3. Then the matrix that has to be generated will be: [[1,2,3],[4,5,6],[7,8,9] ] 

In [17]:
import numpy as np
def fun(n,m):
    k = 1
    eye_mat = np.eye(n,m,dtype=int)
    for i in range(n):
        for j in range(m):
            eye_mat[i][j] = int(k)
            k+=1
    print(eye_mat)
    
    return eye_mat
fun(3,3)    
    

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Write a function to reverse odd or even rows in matrix. 
Mat = [[ 1,2,3,4], [5,6,7,8], [9,10,11,12]] 
reverse_matrix(mat,row=”odd”) -> [[ 1,2,3,4], [8,7,6,5], [9,10,11,12]] 
reverse_matrix(mat,row=”even”)-> [[ 4,3,2,1], [5,6,7,8], [12,11,10,9]] 

In [24]:
Mat = [[ 1,2,3,4], [5,6,7,8], [9,10,11,12]]
from copy import deepcopy
def reverse_matrix(mat=None,row=None):
    mat_len = len(mat)
    if row=="odd":
        for i in range(0,mat_len):
            if i%2==1:
                mat[i] = mat[i][::-1]
    
    
    elif row=="even":
        for i in range(0,mat_len):
            if i%2==0:
                mat[i] = mat[i][::-1]
    return mat

print(reverse_matrix(deepcopy(Mat),"odd"))
print(reverse_matrix(deepcopy(Mat),"even"))

[[1, 2, 3, 4], [8, 7, 6, 5], [9, 10, 11, 12]]
[[4, 3, 2, 1], [5, 6, 7, 8], [12, 11, 10, 9]]


[[1, 2, 3, 4], [8, 7, 6, 5], [9, 10, 11, 12]]
[[4, 3, 2, 1], [8, 7, 6, 5], [12, 11, 10, 9]]
